# Generated by Django 5.0.4 on 2024-04-26 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MotorcycleInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorcycle_count', models.IntegerField()),
                ('motorcycle_total_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MotorcycleManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MotorcycleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Sport', 'Sport'), ('Touring', 'Touring'), ('Cruiser', 'Cruiser'), ('Naked', 'Naked'), ('Street', 'Street'), ('Electric', 'Electric'), ('Adventure', 'Adventure'), ('Scooter', 'Scooter'), ('Custom', 'Custom'), ('Classic', 'Classic'), ('Dirt', 'Dirt'), ('Other', 'Other')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=80)),
                ('engine_size', models.IntegerField(blank=True, null=True)),
                ('model_year', models.IntegerField()),
                ('production_year', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(max_length=50)),
                ('kilometrage', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='motorcycle_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motorcycle_manufacturer', to='motorcycles.motorcyclemanufacturer')),
                ('motorcycle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motorcycle_type', to='motorcycles.motorcycletype')),
            ],
        ),
    ]
