# Generated by Django 5.0.4 on 2024-05-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycles', '0003_alter_motorcycle_model_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='fuel',
            field=models.CharField(blank=True, choices=[('G', 'Gasoline'), ('F', 'Flex Fuel'), ('A', 'Alcohol'), ('D', 'Diesel'), ('H', 'Hybrid'), ('E', 'Electric')], max_length=1, null=True),
        ),
    ]
