# Generated by Django 5.0.4 on 2024-04-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('factory_year', models.IntegerField(blank=True, null=True)),
                ('model_year', models.IntegerField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('body_type', models.CharField(max_length=200)),
                ('power', models.IntegerField(blank=True, null=True)),
                ('cylinder_number', models.IntegerField(blank=True, null=True)),
                ('fuel', models.CharField(max_length=200)),
                ('gearbox', models.CharField(max_length=200)),
                ('doors', models.IntegerField(blank=True, null=True)),
                ('quilometers', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
